services:

  champion: 
    image: markw/fair-champion:1.1.7
    environment:
      - TESTHOST=https://tests.ostrails.eu/tests/
      - CHAMPHOST=http://localhost:8383/
    ports:
      - "8383:4567"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



  swagger-converter:
    image: swaggerapi/swagger-converter:latest 
    container_name: swagger-converter  
#    ports:
#      - "8081:8080"  
