name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0' # Adjust to your Ruby version
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: bundle exec rspec
    - name: Generate RDoc
      run: rdoc --output doc lib/algorithm.rb lib/champion_core.rb lib/dcat_extractor.rb lib/routes.rb
    - name: Upload RDoc
      uses: actions/upload-artifact@v4
      with:
        name: rdoc
        path: doc/
        retention-days: 7
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/
